services:
  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD:-root}
      - MYSQL_DATABASE=${DATABASE_NAME:-room-booking}
    ports:
      - "${DATABASE_PORT:-3457}:3306"