spring:
  datasource:
    url: jdbc:mariadb://${DATABASE_HOST:localhost}:${DATABASE_PORT:3457}/${DATABASE_NAME:room-booking}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root}
  application:
    name: room-booking
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: validate

server:
  port: 8080

default-admin-username: ${DEFAULT_ADMIN_USERNAME:admin}
default-admin-password: ${DEFAULT_ADMIN_PASSWORD:admin}