spring:
  datasource:
    url: jdbc:mariadb://${DATABASE_HOST:localhost}:${DATABASE_PORT:3457}/${DATABASE_NAME:room-booking}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root}
  application:
    name: room-booking
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: ${HIBERNATE_FORMAT_SQL:true}
    show-sql: ${JPA_SHOW_SQL:true}

logging:
  level:
    root: ${SPRING_LOG_LEVEL:WARN}