CREATE TABLE Booking
(
    Id              BIGINT UNSIGNED PRIMARY KEY,
    RoomId          BIGINT UNSIGNED NOT NULL,
    CreatedBy       BIGINT UNSIGNED NOT NULL,
    StartTime       TIMESTAMP NOT NULL,
    EndTime         TIMESTAMP NOT NULL,
    Approved        BOOLEAN NOT NULL DEFAULT FALSE,
    ApprovedBy      BIGINT UNSIGNED NOT NULL,
    CreatedAt       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT FK_Booking_Room FOREIGN KEY (RoomId) REFERENCES Room(Id),
    CONSTRAINT FK_Booking_CreatedBy FOREIGN KEY (CreatedBy) REFERENCES Users(Id),
    CONSTRAINT FK_Booking_ApprovedBy FOREIGN KEY (ApprovedBy) REFERENCES Users(Id),
    CONSTRAINT UQ_Booking UNIQUE (RoomId, StartTime, EndTime)
);

CREATE INDEX IX_Booking ON Booking (RoomId, StartTime, EndTime);
CREATE SEQUENCE booking_sequence AS BIGINT INCREMENT BY 1 START WITH 1;